# Generated by Django 5.0.6 on 2024-06-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_id", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ph", models.FloatField()),
                ("water_temperature", models.FloatField()),
                ("tds", models.FloatField(help_text="Total Dissolved Solids")),
            ],
        ),
    ]
